### ISSUE TITLE
New chef_version setting for metadata.rb in Foodcritic 

### ISSUE THREAD

**Issue by lnxchk** [learn-chef/custom_web#5]
Hi!

In the "Quickstart" parts of this tutorial page:
https://learn.chef.io/modules/build-a-custom-resource/linux/virtualbox#/
the tasks are to check that this custom_web cookbook is clean. 

A rule was added to foodcritic earlier this year, FC066, that is enabled by default and reports an error:

[custom_web]$ foodcritic .
Checking 4 files
x...
FC066: Ensure chef_version is set in metadata: ./metadata.rb:1

I'm not sure what the best version setting would be for this cookbook. The change was made in foodcritic here: https://github.com/Foodcritic/foodcritic/pull/528

thanks!

**Comment by tpetchel** [comment]
This was fixed some time ago - sorry I didn't notice or respond to this issue! Thanks for taking the time to report. ;)
